### ISSUE TITLE
Fix 'ComponentLookupError' error when adding a local user

### ISSUE THREAD

**Issue by alecghica** [collective/collective.xmpp.core#15]
When adding a local user this error occur:

`2013-02-05 16:16:01 INFO collective.xmpp.core.protocols Added user local4@localhost BAQzw9q1p4kO
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/BUILDOUT/eggs/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/words/xish/utility.py", line 27, in __call__
    self.method(*nargs, **nkwargs)
  File "/BUILDOUT/eggs/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/words/protocols/jabber/xmlstream.py", line 735, in callback
    d.callback(iq)
  File "/BUILDOUT/eggs/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py", line 368, in callback
    self._startRunCallbacks(result)
  File "/BUILDOUT/eggs/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py", line 464, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/BUILDOUT/eggs/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py", line 551, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/BUILDOUT/eggs/collective.xmpp.core-0.1b4-py2.6.egg/collective/xmpp/core/utils/users.py", line 95, in subscribeToAllUsers
    d = client.admin.getRegisteredUsers()
  File "/BUILDOUT/eggs/collective.xmpp.core-0.1b4-py2.6.egg/collective/xmpp/core/protocols.py", line 173, in getRegisteredUsers
    iq['to'] = users.getXMPPDomain()
  File "/BUILDOUT/eggs/collective.xmpp.core-0.1b4-py2.6.egg/collective/xmpp/core/utils/users.py", line 13, in getXMPPDomain
    registry = getUtility(IRegistry)
  File "/BUILDOUT/eggs/zope.component-3.9.5-py2.6.egg/zope/component/_api.py", line 169, in getUtility
    raise ComponentLookupError(interface, name)
zope.component.interfaces.ComponentLookupError: (<InterfaceClass plone.registry.interfaces.IRegistry>, '')`

The error does not block any zope process so is not a critical issue, the process of adding local users works just fine. Is just an error when try to get XMPP registry settings.

**Comment by alecghica** [comment]
This may be related to #11 but I dont have any LDAP dev environment right now to test it.
I have the fix on my fork already but I try running the tests (I plan to update them) but with no success. I get this while running the tests:

`File "/BUILDOUT/eggs/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/base.py", line 680, in startRunning
    raise error.ReactorNotRestartable()
ReactorNotRestartable`

@jcbrand you can give me any help on the above?

**Comment by alecghica** [comment]
Fixed 'ComponentLookupError' error when adding a local user and the pull request was merged on master.
